import { Calendar } from '../components/ingredient/calendar';
import { CardList } from '../components/ingredient/cardlist';
import { Datepicker } from '../components/ingredient/datepicker';
import { DoubleCalendar } from '../components/ingredient/double-calendar';
import { Icon } from '../components/ingredient/icon';
import { Image } from '../components/ingredient/image';
import { Input } from '../components/ingredient/input';
import { Menu } from '../components/ingredient/menu';
import { Paragraph } from '../components/ingredient/paragraph';
import { Profile } from '../components/ingredient/profile';
import { Search } from '../components/ingredient/search';
import { Select } from '../components/ingredient/select';
import { Sort } from '../components/ingredient/sort';
import { Text } from '../components/ingredient/text';
import { TimePicker } from '../components/ingredient/timepicker';
import { Toggle } from '../components/ingredient/toggle';
import { Translate } from '../components/ingredient/translate';
import { ContentTab } from '../components/kit/content-tab';
import { Dialog } from '../components/kit/dialog';
import { Dropdown } from '../components/kit/dropdown';
import { Layout } from '../components/kit/layout';
import { Papers } from '../components/kit/papers';
import { Print } from '../components/kit/print';
import { RadioCard } from '../components/kit/radio-card';
import { Row } from '../components/kit/row';
import { SortGroup } from '../components/kit/sort-group';
import { Translation } from '../components/kit/translation';

export type CSearch = Search;
export type CSelect = Select;
export type CImage = Image;
export type CLayout = Layout;
export type CTranslation = Translation;
export type CTranslate = Translate;
export type CText = Text;
export type CPrint = Print;
export type CContentTab = ContentTab;
export type CCalendar = Calendar;
export type CSort = Sort;
export type CSortGroup = SortGroup;
export type CDoubleCalendar = DoubleCalendar;
export type CDropdown = Dropdown;
export type CInput = Input;
export type CProfile = Profile;
export type CCardList = CardList;
export type CParagraph = Paragraph;
export type CPapers = Papers;
export type CRow = Row;
export type CTimepicker = TimePicker;
export type CMenu = Menu;
export type CDialog = Dialog;
export type CDatepicker = Datepicker;
export type CToggle = Toggle;
export type CIcon = Icon;
export type CRadioCard = RadioCard;
